nits

diff --git a/infra/base-images/base-builder/compile_afl b/infra/base-images/base-builder/compile_afl
--- a/infra/base-images/base-builder/compile_afl
+++ b/infra/base-images/base-builder/compile_afl
@@ -69,6 +69,7 @@ function afl_set_oss_fuzz_opts() {
   rm -f "$OUT/afl_cmplog.txt"
 
   opt=$1
+  echo "Using AFL option $opt"
   if [ $opt == "OPT1" ]; then
     afl_env1
   elif [ $opt == "OPT2" ]; then
@@ -94,69 +95,69 @@ function afl_set_oss_fuzz_opts() {
   elif [ $opt == "OPT9" ]; then
     afl_env4
   fi
-
-  # Create a dictionary if one is wanted.
-  test "$AFL_ENABLE_DICTIONARY" = "1" && {
-    export AFL_LLVM_DICT2FILE="$OUT/afl++.dict"
-  }
 }
 
 if [[ ! -z ${AFL_OSSFUZZ_OPT} ]]; then
   afl_set_oss_fuzz_opts ${AFL_OSSFUZZ_OPT}
-fi
-
-# To analyze build failures and set specific AFL++ settings, set
-# `export AFL_SKIP_OSSFUZZ=1`
-# The 'env|grep' setup ensures we do not trigger the linter.
-env | egrep -q '^AFL_SKIP_OSSFUZZ=' || {
-
-  # The variables need to be set to "1" here - or before running this script.
-  # AFL++ configuration options.
-  export AFL_LLVM_MODE_WORKAROUND=0
-  export AFL_ENABLE_DICTIONARY=0
-  export AFL_ENABLE_CMPLOG=1
-  export AFL_LAF_CHANCE=5
-
-  #
-  # AFL++ compile option roulette. It is OK if they all happen together.
-  #
-
-  # 20% chance for CTX-2 coverage instrumentation (Caller conTeXt sensitive
-  # edge coverage).
-  test $(($RANDOM % 100)) -lt 20 && {
-    export AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2
-    export AFL_ENABLE_CMPLOG=0
-    # we increase the chance for LAF because we do not do CMPLOG with CTX
-    export AFL_LAF_CHANCE=30
-  }
-
-  # 40% chance to create a dictionary.
-  test $(($RANDOM % 100)) -lt 40 && {
-    export AFL_ENABLE_DICTIONARY=1
-  }
-
-  # 60% chance to perform CMPLOG/REDQUEEN.
-  rm -f "$OUT/afl_cmplog.txt"
-  test "$AFL_ENABLE_CMPLOG" = "1" -a $(($RANDOM % 100)) -lt 60 && {
-    export AFL_LLVM_CMPLOG=1
-    touch "$OUT/afl_cmplog.txt"
-  }
-
-  # chance to perform COMPCOV/LAF_INTEL - if CMPLOG is not enabled.
-  test $(($RANDOM % 100)) -lt $AFL_LAF_CHANCE -a "$AFL_ENABLE_CMPLOG" = "0" && {
-    export AFL_LLVM_LAF_ALL=1
-  }
-
-  #
-  # End of AFL++ compile option roulette
-  #
 
   # Create a dictionary if one is wanted.
   test "$AFL_ENABLE_DICTIONARY" = "1" && {
     export AFL_LLVM_DICT2FILE="$OUT/afl++.dict"
   }
+else
+  # To analyze build failures and set specific AFL++ settings, set
+  # `export AFL_SKIP_OSSFUZZ=1`
+  # The 'env|grep' setup ensures we do not trigger the linter.
+  env | egrep -q '^AFL_SKIP_OSSFUZZ=' || {
 
-}
+    # The variables need to be set to "1" here - or before running this script.
+    # AFL++ configuration options.
+    export AFL_LLVM_MODE_WORKAROUND=0
+    export AFL_ENABLE_DICTIONARY=0
+    export AFL_ENABLE_CMPLOG=1
+    export AFL_LAF_CHANCE=5
+
+    #
+    # AFL++ compile option roulette. It is OK if they all happen together.
+    #
+
+    # 20% chance for CTX-2 coverage instrumentation (Caller conTeXt sensitive
+    # edge coverage).
+    test $(($RANDOM % 100)) -lt 20 && {
+      export AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2
+      export AFL_ENABLE_CMPLOG=0
+      # we increase the chance for LAF because we do not do CMPLOG with CTX
+      export AFL_LAF_CHANCE=30
+    }
+
+    # 40% chance to create a dictionary.
+    test $(($RANDOM % 100)) -lt 40 && {
+      export AFL_ENABLE_DICTIONARY=1
+    }
+
+    # 60% chance to perform CMPLOG/REDQUEEN.
+    rm -f "$OUT/afl_cmplog.txt"
+    test "$AFL_ENABLE_CMPLOG" = "1" -a $(($RANDOM % 100)) -lt 60 && {
+      export AFL_LLVM_CMPLOG=1
+      touch "$OUT/afl_cmplog.txt"
+    }
+
+    # chance to perform COMPCOV/LAF_INTEL - if CMPLOG is not enabled.
+    test $(($RANDOM % 100)) -lt $AFL_LAF_CHANCE -a "$AFL_ENABLE_CMPLOG" = "0" && {
+      export AFL_LLVM_LAF_ALL=1
+    }
+
+    #
+    # End of AFL++ compile option roulette
+    #
+
+    # Create a dictionary if one is wanted.
+    test "$AFL_ENABLE_DICTIONARY" = "1" && {
+      export AFL_LLVM_DICT2FILE="$OUT/afl++.dict"
+    }
+
+  }
+fi
 
 # In case afl-clang-fast ever breaks, this is a workaround:
 test "$AFL_LLVM_MODE_WORKAROUND" = "1" && {
