infra: fix python coverage logic (#7616)
* infra: write python coverage to correct folder

Ref: https://github.com/google/oss-fuzz/issues/7615

* fix issues when atheris does not exit gracefully

diff --git a/infra/base-images/base-runner/coverage b/infra/base-images/base-runner/coverage
--- a/infra/base-images/base-runner/coverage
+++ b/infra/base-images/base-runner/coverage
@@ -156,6 +156,11 @@ function run_python_fuzz_target {
   local zipped_sources="$DUMPS_DIR/$target.deps.zip"
   local corpus_real="$CORPUS_DIR/${target}"
   $OUT/$target.pkg $corpus_real -atheris_runs=$(ls -la $corpus_real | wc -l)
+  if (( $? != 0 )); then
+    echo "Error happened getting coverage of $target"
+    echo "This is likely because Atheris did not exit gracefully"
+    return 0
+  fi
   mv .coverage $OUT/.coverage_$target
 }
 
@@ -302,7 +307,7 @@ elif [[ $FUZZING_LANGUAGE == "python" ]]; then
   cd $PYCOVDIR
   python3 /usr/local/bin/python_coverage_runner_help.py combine .coverage_*
   python3 /usr/local/bin/python_coverage_runner_help.py html
-  mv htmlcov $REPORT_ROOT_DIR/
+  mv htmlcov/* $REPORT_PLATFORM_DIR/
 elif [[ $FUZZING_LANGUAGE == "jvm" ]]; then
 
   # From this point on the script does not tolerate any errors.
