feat: coverage collection from corpus snapshot, support Python

diff --git a/infra/base-images/base-runner/coverage_snapshot b/infra/base-images/base-runner/coverage_snapshot
--- a/infra/base-images/base-runner/coverage_snapshot
+++ b/infra/base-images/base-runner/coverage_snapshot
@@ -198,20 +198,38 @@ function run_go_fuzz_target {
 
 function run_python_fuzz_target {
   local target=$1
-  local zipped_sources="$DUMPS_DIR/$target.deps.zip"
-  local corpus_real="$CORPUS_DIR/${target}"
-  # Write dummy stats file
-  echo "{}" > "$FUZZER_STATS_DIR/$target.json"
 
-  # Run fuzzer
-  $OUT/$target $corpus_real -atheris_runs=$(ls -la $corpus_real | wc -l) > $LOGS_DIR/$target.log 2>&1
-  if (( $? != 0 )); then
-    echo "Error happened getting coverage of $target"
-    echo "This is likely because Atheris did not exit gracefully"
-    cat $LOGS_DIR/$target.log
+  local corpus_base="$CORPUS_DIR/${target}_backup"
+
+  local corpus_snapshots=()
+  while IFS= read -r -d '' dir; do
+    corpus_snapshots+=("$dir")
+  done < <(find "$corpus_base" -maxdepth 1 -type d -name 'backup_*' -print0)
+
+  # Check if any snapshots are found
+  if [ ${#corpus_snapshots[@]} -eq 0 ]; then
+    echo "No corpus snapshots found for target $target in $corpus_base"
     return 0
   fi
-  mv .coverage $OUT/.coverage_$target
+
+  # Process each snapshot independently
+  for corpus_dir in "${corpus_snapshots[@]}"; do
+    snapshot_name=$(basename $corpus_dir)
+
+    local zipped_sources="$DUMPS_DIR/${target}/${snapshot_name}.deps.zip"
+    local corpus_real=$corpus_dir
+    # # Write dummy stats file
+    # echo "{}" > "$FUZZER_STATS_DIR/${target}_${snapshot_name}.json"
+
+    $OUT/$target $corpus_real -atheris_runs=$(ls -la $corpus_real | wc -l) > $LOGS_DIR/${target}_${snapshot_name}.log 2>&1
+    if (( $? != 0 )); then
+      echo "Error happened getting coverage of $target"
+      echo "This is likely because Atheris did not exit gracefully"
+      cat $LOGS_DIR/${target}_${snapshot_name}.log
+      return 0
+    fi
+    mv .coverage $OUT/.coverage_${target}_${snapshot_name}
+  done
 }
 
 function run_java_fuzz_target {
@@ -448,37 +466,37 @@ if [[ $FUZZING_LANGUAGE == "go" ]]; then
 elif [[ $FUZZING_LANGUAGE == "python" ]]; then
   # Extract source files from all dependency zip folders
   mkdir -p /pythoncovmergedfiles/medio
-  PYCOVDIR=/pycovdir/
-  mkdir $PYCOVDIR
   for fuzzer in $FUZZ_TARGETS; do
     fuzzer_deps=${fuzzer}.pkg.deps.zip
     unzip $OUT/${fuzzer_deps}
     rsync -r ./medio /pythoncovmergedfiles/medio
     rm -rf ./medio
 
-    # Translate paths in unzipped folders to paths that we can use
-    mv $OUT/.coverage_$fuzzer .coverage
-    python3 /usr/local/bin/python_coverage_runner_help.py translate /pythoncovmergedfiles/medio
-    cp .new_coverage $PYCOVDIR/.coverage_$fuzzer
-    cp .new_coverage $OUT/coverage_d_$fuzzer
+    coverage_snapshots=()
+    while IFS= read -r -d '' file; do
+      coverage_snapshots+=("$file")
+    done < <(find "$OUT" -maxdepth 1 -type f -name ".coverage_${fuzzer}_backup_*" -print0)
+
+    ls -la $OUT
+
+    # Check if any snapshots are found
+    if [ ${#coverage_snapshots[@]} -eq 0 ]; then
+      echo "No coverage snapshots found for target $fuzzer in $OUT"
+      return 0
+    fi
+
+    for coverage_snapshot in "${coverage_snapshots[@]}"; do
+      snapshot_name=$(echo "$coverage_snapshot" | awk -F'_' '{print $NF}')
+      # Translate paths in unzipped folders to paths that we can use
+      mv $coverage_snapshot .coverage
+      python3 /usr/local/bin/python_coverage_runner_help.py translate /pythoncovmergedfiles/medio
+
+      # Generate coverage report for this snapshot
+      python3 /usr/local/bin/python_coverage_runner_help.py json --data-file=.new_coverage -o ${TEXTCOV_REPORT_DIR}/${fuzzer}/${snapshot_name}.json
+
+    done
   done
 
-  # Combine coverage
-  cd $PYCOVDIR
-  python3 /usr/local/bin/python_coverage_runner_help.py combine .coverage_*
-  python3 /usr/local/bin/python_coverage_runner_help.py html
-  # Produce all_cov file used by fuzz introspector.
-  python3 /usr/local/bin/python_coverage_runner_help.py json -o ${TEXTCOV_REPORT_DIR}/all_cov.json
-
-  # Generate .json with similar format to llvm-cov output.
-  python3 /usr/local/bin/python_coverage_runner_help.py \
-      convert-to-summary-json ${TEXTCOV_REPORT_DIR}/all_cov.json $SUMMARY_FILE
-
-  # Copy coverage date out
-  cp htmlcov/status.json ${TEXTCOV_REPORT_DIR}/html_status.json
-
-  mv htmlcov/* $REPORT_PLATFORM_DIR/
-  mv .coverage_* $REPORT_PLATFORM_DIR/
 elif [[ $FUZZING_LANGUAGE == "jvm" ]]; then
   # Skip operations
   echo "Finished generating code coverage report for JVM fuzz targets."
