Always run all checks and store all errors + clean up the code and add comments

diff --git a/infra/base-images/base-runner/test_all b/infra/base-images/base-runner/test_all
--- a/infra/base-images/base-runner/test_all
+++ b/infra/base-images/base-runner/test_all
@@ -15,20 +15,21 @@
 #
 ################################################################################
 
-# Test every fuzzer. Fails on first fuzzer failure.
-
+# Test all fuzz targets in the $OUT/ dir.
 TOTAL_TARGETS_COUNT=0
 
+# Number of CPUs available, this is needed for running tests in parallel.
 NPROC=$(nproc)
+
+# Directories where bad build check results will be written to.
 VALID_TARGETS_DIR="/tmp/valid_fuzz_targets"
 BROKEN_TARGETS_DIR="/tmp/broken_fuzz_targets"
-
 rm -rf $VALID_TARGETS_DIR
 rm -rf $BROKEN_TARGETS_DIR
-
 mkdir $VALID_TARGETS_DIR
 mkdir $BROKEN_TARGETS_DIR
 
+# Main loop that iterates through all fuzz targets and runs the check.
 for FUZZER_BINARY in $(find $OUT/ -executable -type f); do
   if file "$FUZZER_BINARY" | grep -v ELF > /dev/null 2>&1; then
     continue
@@ -53,10 +54,13 @@ for FUZZER_BINARY in $(find $OUT/ -executable -type f); do
     fi
   fi
 
+  # Launch bad build check process in the background.
   bad_build_check $FUZZER_BINARY $VALID_TARGETS_DIR $BROKEN_TARGETS_DIR &
 
+  # Count total number of fuzz targets being tested.
   TOTAL_TARGETS_COUNT=$[$TOTAL_TARGETS_COUNT+1]
 
+  # Do not spawn more processes than the number of CPUs available.
   n_child_proc=$(jobs -p | wc -l)
   while [ "$n_child_proc" -eq "$NPROC" ]; do
     sleep 4
@@ -64,17 +68,21 @@ for FUZZER_BINARY in $(find $OUT/ -executable -type f); do
   done
 done
 
+# Wait for background processes to finish.
 wait
 
-VALID_TARGETS_COUNT=$(ls $VALID_TARGETS_DIR | wc -l)
-BROKEN_TARGETS_COUNT=$(ls $BROKEN_TARGETS_DIR | wc -l)
-
+# Sanity check in case there are no fuzz targets in the $OUT/ dir.
 if [ "$TOTAL_TARGETS_COUNT" -eq "0" ]; then
   echo "ERROR: no fuzzers found in $OUT/"
   ls -al $OUT
   exit 1
 fi
 
+# Calculate number of valid and broken fuzz targets.
+VALID_TARGETS_COUNT=$(ls $VALID_TARGETS_DIR | wc -l)
+BROKEN_TARGETS_COUNT=$(ls $BROKEN_TARGETS_DIR | wc -l)
+
+# Sanity check to make sure that bad build check doesn't skip any fuzz target.
 if [ "$TOTAL_TARGETS_COUNT" -ne "$[$VALID_TARGETS_COUNT+$BROKEN_TARGETS_COUNT]" ]; then
   echo "ERROR: bad_build_check seems to have a bug, total number of fuzz" \
        "does not match number of fuzz targets tested."
@@ -87,21 +95,25 @@ if [ "$TOTAL_TARGETS_COUNT" -ne "$[$VALID_TARGETS_COUNT+$BROKEN_TARGETS_COUNT]" 
   exit 1
 fi
 
-BROKEN_TARGETS_PERCENTAGE=$[$BROKEN_TARGETS_COUNT*100/$TOTAL_TARGETS_COUNT]
-
-RETURN_VALUE=0
-
-if [ "$BROKEN_TARGETS_PERCENTAGE" -gt "90" ]; then
-  echo "ERROR: $BROKEN_TARGETS_PERCENTAGE % of fuzz targets seem to be broken"
-  RETURN_VALUE=1
-else
-  echo "$TOTAL_TARGETS_COUNT fuzzers total, $BROKEN_TARGETS_COUNT seem to be" \
-       "broken ($BROKEN_TARGETS_PERCENTAGE%)"
+# Build info about all broken fuzz targets (if any).
+if [ "$BROKEN_TARGETS_COUNT" -gt "0" ]; then
+  echo "Broken fuzz targets ($BROKEN_TARGETS_COUNT):"
+  for target in $(ls $BROKEN_TARGETS_DIR); do
+    echo "${target}:"
+    cat ${BROKEN_TARGETS_DIR}/${target}
+  done
 fi
 
-if [ "$BROKEN_TARGETS_COUNT" -gt "0" ]; then
-  echo "Broken fuzz targets ($BROKEN_TARGETS_COUNT)"
-  for target in $(ls $BROKEN_TARGETS_DIR); do
-    echo "${target}: $(cat ${BROKEN_TARGETS_DIR}/${target})"
-  done
+# Calculate the percentage of broken fuzz targets and make the finel decision.
+BROKEN_TARGETS_PERCENTAGE=$[$BROKEN_TARGETS_COUNT*100/$TOTAL_TARGETS_COUNT]
+
+
+if [ "$BROKEN_TARGETS_PERCENTAGE" -gt "90" ]; then
+  echo "ERROR: $BROKEN_TARGETS_PERCENTAGE% of fuzz targets seem to be broken." \
+       "See the list above for a detailed information."
+  exit 1
+else
+  echo "$TOTAL_TARGETS_COUNT fuzzers total, $BROKEN_TARGETS_COUNT seem to be" \
+       "broken ($BROKEN_TARGETS_PERCENTAGE%)."
+  exit 0
 fi
