[infra] reproduce command (#53)
runs specified fuzzer with `/testcase` as input.

example:

```
docker run -v <local_file>:/testcase -t ossfuzz/libxml2 reproduce libxml2_xml_read_memory_fuzzer
```

diff --git a/infra/base-images/base-libfuzzer/reproduce b/infra/base-images/base-libfuzzer/reproduce
--- a/infra/base-images/base-libfuzzer/reproduce
+++ b/infra/base-images/base-libfuzzer/reproduce
@@ -1,3 +1,4 @@
+#!/bin/bash -eux
 # Copyright 2016 Google Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -14,21 +15,19 @@
 #
 ################################################################################
 
-FROM ossfuzz/base-clang
-MAINTAINER mike.aizatsky@gmail.com
-RUN apt-get install -y libc6-dev libtool git subversion jq
+FUZZER=$1
+shift
+TESTCASE="/testcase"
 
-ENV SANITIZER_FLAGS="-fsanitize=address"
-ENV COV_FLAGS="-fsanitize-coverage=edge,indirect-calls,8bit-counters"
+if [ ! -f $TESTCASE ]; then
+  echo "Error: $TESTCASE not found, use: docker run -v <path>:$TESTCASE ..."
+  exit 1
+fi
 
-ENV ASAN_OPTIONS="symbolize=1:detect_leaks=0"
-ENV FUZZER_LDFLAGS "-Wl,-whole-archive /usr/local/lib/libc++.a /usr/local/lib/libc++abi.a -Wl,-no-whole-archive"
 
-RUN mkdir /out && chmod a+w /out
+compile
+export PATH=/out:$PATH
+cd /out
 
-RUN mkdir /src/bin
-COPY compile srcmap reproduce run test /src/bin/
-ENV PATH=/src/bin:$PATH
-WORKDIR /src
-CMD ["compile"]
+$FUZZER $@ $TESTCASE
 
